[General]
# Green stone and copper.

Font="Plus Jakarta Sans"
FontSize="11"

Background="backgrounds/malachite.jpg"
BackgroundColor="#00140e"
Blur="0.05"
Dim="0.20"

ClockSize="20"
TimeTextColor="#eafffb"
DateTextColor="#bdf5ef"

HourFormat="24h"
ShowDate="true"
ShowWeekday="true"
ShowSeconds="false"

Radius="24"
RadiusSmall="10"
AnimationDuration="300"

FieldOpacity="0.25"
FormOpacity="0.00"

FormBackgroundColor="#00140e"
LoginFieldBackgroundColor="#039687"
LoginFieldTextColor="#eafffb"
PlaceholderTextColor="#7fbcb3"

FocusRingColor="#009a93"
FocusRingWidth="2"

LoginButtonBackgroundColor="#009a93"
LoginButtonTextColor="#00140e"
HoverLoginButtonBackgroundColor="#19b3ae"

SystemButtonsIconsColor="#bdf5ef"
HoverSystemButtonsIconsColor="#19b3ae"
EnvironmentButtonTextColor="#bdf5ef"
HoverEnvironmentButtonTextColor="#19b3ae"

DropdownTextColor="#bdf5ef"
DropdownSelectedTextColor="#00140e"
DropdownBackgroundColor="#001a12"
DropdownSelectedBackgroundColor="#009a93"
DropdownBorderColor="#016964"

WarningTextColor="#19b3ae"

AvatarSize="128"
AvatarRadius="64"
AvatarBorderWidth="2"
AvatarBorderColor="#016964"

ShowLogo="false"
DisableUserList="false"
