[General]
# Pale petals on ink.

Font="Plus Jakarta Sans"
FontSize="11"

Background="backgrounds/sakura.jpg"
BackgroundColor="#21222C"
Blur="0.4"
Dim="0.20"

ClockSize="20"
TimeTextColor="#ffffff"
DateTextColor="#ffffff"

HourFormat="24h"
ShowDate="true"
ShowWeekday="true"
ShowSeconds="false"

Radius="24"
RadiusSmall="10"
AnimationDuration="300"

FieldOpacity="0.25"
FormOpacity="0.00"

FormBackgroundColor="#21222C"
LoginFieldBackgroundColor="#0B0D12"
LoginFieldTextColor="#e0e0e0"
PlaceholderTextColor="#9aa0a6"

FocusRingColor="#282a32"
FocusRingWidth="2"

LoginButtonBackgroundColor="#282a32"
LoginButtonTextColor="#ffffff"
HoverLoginButtonBackgroundColor="#3a3c44"

SystemButtonsIconsColor="#F8F8F2"
HoverSystemButtonsIconsColor="#C0C0C0"
EnvironmentButtonTextColor="#F8F8F2"
HoverEnvironmentButtonTextColor="#C0C0C0"

DropdownTextColor="#ffffff"
DropdownSelectedTextColor="#ffffff"
DropdownBackgroundColor="#21222C"
DropdownSelectedBackgroundColor="#343746"
DropdownBorderColor="#8ab4f8"

WarningTextColor="#3a3c44"

AvatarSize="128"
AvatarRadius="64"
AvatarBorderWidth="2"
AvatarBorderColor="#8ab4f8"

ShowLogo="false"
DisableUserList="false"
